Repository GyeongNam/Alioth-Back, pull requests merged in 2024-04, with the labels that each got.

#29 Hhj/testcase and fix3
  server/src/main/java/com/alioth/server/common/config/SecurityConfig.java
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/board/domain/Board.java
  server/src/main/java/com/alioth/server/domain/member/controller/SalesMemberController.java
  server/src/main/java/com/alioth/server/domain/member/domain/SalesMembers.java
  server/src/main/java/com/alioth/server/domain/member/dto/req/SMAdminUpdateReqDto.java
  server/src/main/java/com/alioth/server/domain/member/dto/req/SalesMemberUpdatePerformanceReview.java
  server/src/main/java/com/alioth/server/domain/member/dto/req/SalesMemberUpdateReqDto.java
  server/src/main/java/com/alioth/server/domain/member/dto/res/SMTeamListResDto.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
  server/src/main/java/com/alioth/server/domain/team/controller/TeamController.java
  server/src/main/java/com/alioth/server/domain/team/domain/Team.java
  server/src/main/java/com/alioth/server/domain/team/dto/TeamAddMemberDto.java
  server/src/main/java/com/alioth/server/domain/team/dto/TeamCreateDto.java
  server/src/main/java/com/alioth/server/domain/team/dto/TeamDto.java
  server/src/main/java/com/alioth/server/domain/team/dto/TeamReqDto.java
  server/src/main/java/com/alioth/server/domain/team/dto/TeamResDto.java
  server/src/main/java/com/alioth/server/domain/team/service/TeamService.java
  server/src/test/java/com/alioth/server/domain/board/service/BoardServiceTest.java
  server/src/test/java/com/alioth/server/domain/member/service/SalesMemberServiceTest.java
  server/src/test/java/com/alioth/server/domain/team/service/TeamServiceTest.java
Labels: 🔼백엔드-개발, ✅테스트, 🍀코드리뷰

#31 JGN/AWS-SMS
  server/.gitignore
  server/build.gradle
  server/src/main/java/com/alioth/server/common/aws/SMSService.java
  server/src/main/java/com/alioth/server/domain/login/controller/LoginController.java
Labels: 🔼백엔드-개발

#32 Statistics set02
  server/src/main/java/com/alioth/server/common/init/DataInitialization.java
  server/src/main/java/com/alioth/server/domain/dummy/domain/ContractStatus.java
  server/src/main/java/com/alioth/server/domain/dummy/domain/InsuranceProductCategory.java
  server/src/main/java/com/alioth/server/domain/target/sm/domain/SMSalesTarget.java
  server/src/main/java/com/alioth/server/domain/target/sm/repository/SMSalesTargetRepository.java
  server/src/main/java/com/alioth/server/domain/target/team/domain/TeamTarget.java
  server/src/main/java/com/alioth/server/domain/target/team/repository/TeamTargetRepository.java
  statistics/build.gradle
  statistics/src/main/java/com/alioth/statistics/common/config/jpa/JPAFactoryConfig.java
  statistics/src/main/java/com/alioth/statistics/common/domain/BaseEntity.java
  statistics/src/main/java/com/alioth/statistics/common/response/CommonResponse.java
  statistics/src/main/java/com/alioth/statistics/common/response/ExceptionResponse.java
  statistics/src/main/java/com/alioth/statistics/domain/board/domain/Board.java
  statistics/src/main/java/com/alioth/statistics/domain/board/domain/BoardType.java
  statistics/src/main/java/com/alioth/statistics/domain/board/repository/BoardRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/contract/domain/Contract.java
  statistics/src/main/java/com/alioth/statistics/domain/contract/domain/Renewal.java
  statistics/src/main/java/com/alioth/statistics/domain/contract/repository/ContractRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/contract/repository/RenewalRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/controller/StatisticsController.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/controller/AchievementRateController.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/domain/ContractMembers.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/domain/ContractStatus.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/domain/Custom.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/domain/InsuranceProduct.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/domain/InsuranceProductCategory.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/domain/PaymentFrequency.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/repository/ContractMembersRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/repository/CustomRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/repository/InsuranceProductRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/service/CompanyAchievementRateService.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/service/SMAchievementRateService.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/service/TeamAchievementRateService.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/service/impl/CompanyAchievementRateServiceImpl.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/service/impl/SMAchievementRateServiceImpl.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/service/impl/TeamAchievementRateServiceImpl.java
  statistics/src/main/java/com/alioth/statistics/domain/member/domain/SalesMemberType.java
  statistics/src/main/java/com/alioth/statistics/domain/member/domain/SalesMembers.java
  statistics/src/main/java/com/alioth/statistics/domain/member/repository/SalesMemberRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/schedule/domain/Schedule.java
  statistics/src/main/java/com/alioth/statistics/domain/schedule/domain/ScheduleType.java
  statistics/src/main/java/com/alioth/statistics/domain/schedule/repository/ScheduleRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/target/sm/domain/SMSalesTarget.java
  statistics/src/main/java/com/alioth/statistics/domain/target/sm/repository/SMSalesTargetRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/target/team/domain/TeamTarget.java
  statistics/src/main/java/com/alioth/statistics/domain/target/team/repository/TeamTargetRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/team/domain/Team.java
  statistics/src/main/java/com/alioth/statistics/domain/team/repository/TeamRepository.java
  statistics/src/main/java/com/alioth/statistics/service/MemberRankService.java
  statistics/src/main/java/com/alioth/statistics/service/StatisticsRankService.java
  statistics/src/main/resources/application.yml
  statistics/src/test/java/com/alioth/statistics/StatisticsApplicationTests.java
  statistics/src/test/java/com/alioth/statistics/service/AchievementRateAllTest.java
  statistics/src/test/java/com/alioth/statistics/service/AchievementRateTeamTest.java
  statistics/src/test/java/com/alioth/statistics/service/AchievementRateTest.java
  statistics/src/test/java/com/alioth/statistics/service/ItemRankTest.java
  statistics/src/test/java/com/alioth/statistics/service/MemberRankServiceTest.java
Labels: 🔼백엔드-개발, ✅테스트, 🍀코드리뷰

#33 Statistics fix
  statistics/src/main/java/com/alioth/statistics/domain/dummy/service/impl/SMAchievementRateServiceImpl.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/service/impl/TeamAchievementRateServiceImpl.java
  statistics/src/test/java/com/alioth/statistics/service/AchievementRateTeamTest.java
  statistics/src/test/java/com/alioth/statistics/service/AchievementRateTest.java
  statistics/src/test/java/com/alioth/statistics/service/MemberRankServiceTest.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#36 계약 서비스 API 작성
  statistics/src/main/java/com/alioth/statistics/domain/dummy/controller/AchievementRateController.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/controller/InsuranceProductController.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/service/achievementrate/CompanyAchievementRateService.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/service/achievementrate/SMAchievementRateService.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/service/achievementrate/TeamAchievementRateService.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/service/achievementrate/impl/CompanyAchievementRateServiceImpl.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/service/achievementrate/impl/SMAchievementRateServiceImpl.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/service/achievementrate/impl/TeamAchievementRateServiceImpl.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/service/insuranceproduct/InsuranceProductService.java
  statistics/src/main/java/com/alioth/statistics/domain/dummy/service/insuranceproduct/impl/InsuranceProductRankService.java
Labels: 🔼백엔드-개발, ✅테스트, 🍀코드리뷰

#34 [feat]:FCM 백앤드구현
  server/.gitignore
  server/build.gradle
  server/src/main/java/com/alioth/server/common/config/FireBaseConfig.java
  server/src/main/java/com/alioth/server/common/config/SecurityConfig.java
  server/src/main/java/com/alioth/server/common/firebase/FcmController.java
  server/src/main/java/com/alioth/server/common/firebase/FcmMessageDto.java
  server/src/main/java/com/alioth/server/common/firebase/FcmSendDto.java
  server/src/main/java/com/alioth/server/common/firebase/FcmService.java
  server/src/main/java/com/alioth/server/common/firebase/FcmServiceImpl.java
  server/src/main/java/com/alioth/server/domain/login/dto/req/LoginReqDto.java
  server/src/main/java/com/alioth/server/domain/login/service/impl/LoginServiceImpl.java
  server/src/main/java/com/alioth/server/domain/login/service/impl/LogoutServiceImpl.java
  server/src/main/resources/application.yml
Labels: 🍀코드리뷰

#39 팀 달성 금액 순위 작성
  statistics/src/main/java/com/alioth/statistics/controller/TeamController.java
  statistics/src/main/java/com/alioth/statistics/service/team/TeamRankService.java
  statistics/src/main/java/com/alioth/statistics/service/team/impl/TeamMoneyRankService.java
  statistics/src/main/resources/application.yml
  statistics/src/test/java/com/alioth/statistics/service/team/impl/TeamMoneyRankServiceTest.java
Labels: 🔼백엔드-개발, ✅테스트, 🍀코드리뷰

#40 Psj/cancellation
  statistics/src/main/java/com/alioth/statistics/controller/CancellationController.java
  statistics/src/main/java/com/alioth/statistics/controller/SalesMemberRankController.java
  statistics/src/main/java/com/alioth/statistics/controller/TeamRankController.java
  statistics/src/main/java/com/alioth/statistics/domain/contract/repository/ContractRepository.java
  statistics/src/main/java/com/alioth/statistics/service/cencellation/CancellationRankService.java
  statistics/src/main/java/com/alioth/statistics/service/cencellation/CancellationService.java
  statistics/src/main/java/com/alioth/statistics/service/cencellation/impl/HqCancellationService.java
  statistics/src/main/java/com/alioth/statistics/service/cencellation/impl/SmCancellationRankService.java
  statistics/src/main/java/com/alioth/statistics/service/cencellation/impl/SmCancellationService.java
  statistics/src/main/java/com/alioth/statistics/service/cencellation/impl/TeamCancellationService.java
  statistics/src/test/java/com/alioth/statistics/service/cencellation/SMCancellationServiceTest.java
  statistics/src/test/java/com/alioth/statistics/service/cencellation/impl/HqCancellationServiceTest.java
  statistics/src/test/java/com/alioth/statistics/service/cencellation/impl/SmCancellationRankServiceTest.java
  statistics/src/test/java/com/alioth/statistics/service/cencellation/impl/TeamCancellationServiceTest.java
Labels: 🔼백엔드-개발, ✅테스트, 🍀코드리뷰

#41 JGN/PR-error2
  server/src/main/java/com/alioth/server/common/config/FireBaseConfig.java
Labels: ✅기타작업

#42 고과 평가 + 스웨거설정
  server/settings.gradle
  server/src/main/java/com/alioth/server/common/config/FireBaseConfig.java
  server/src/main/java/com/alioth/server/common/response/CommonResponse.java
  server/src/main/java/com/alioth/server/domain/team/domain/Team.java
  statistics/build.gradle
  statistics/src/main/java/com/alioth/statistics/common/config/swagger/SwaggerConfig.java
  statistics/src/main/java/com/alioth/statistics/controller/CancellationController.java
  statistics/src/main/java/com/alioth/statistics/controller/PerformanceReviewController.java
  statistics/src/main/java/com/alioth/statistics/domain/member/dto/res/MemberPerformanceReviewResDto.java
  statistics/src/main/java/com/alioth/statistics/domain/member/dto/res/TeamPerformanceReviewResDto.java
  statistics/src/main/java/com/alioth/statistics/domain/member/repository/SalesMemberRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/team/domain/Team.java
  statistics/src/main/java/com/alioth/statistics/service/cencellation/SmCancellationService.java
  statistics/src/main/java/com/alioth/statistics/service/cencellation/TeamCancellationService.java
  statistics/src/main/java/com/alioth/statistics/service/cencellation/rank/CancellationRankService.java
  statistics/src/main/java/com/alioth/statistics/service/cencellation/rank/SmCancellationRankService.java
  statistics/src/main/java/com/alioth/statistics/service/performance/PerformanceReviewService.java
  statistics/src/main/java/com/alioth/statistics/service/performance/PerformanceReviewServiceImpl.java
  statistics/src/main/resources/application.yml
  statistics/src/test/java/com/alioth/statistics/service/cencellation/rank/HqCancellationServiceTest.java
  statistics/src/test/java/com/alioth/statistics/service/cencellation/rank/SmCancellationRankServiceTest.java
  statistics/src/test/java/com/alioth/statistics/service/cencellation/rank/TeamCancellationServiceTest.java
  statistics/src/test/java/com/alioth/statistics/service/performance/SmPerformanceReviewServiceTest.java
  statistics/src/test/java/com/alioth/statistics/service/performance/TeamPerformanceReviewServiceTest.java
Labels: 🔼백엔드-개발, ✅테스트, 🍀코드리뷰, ✅기타작업

#44 [feat]: excel download 기능 구현
  server/build.gradle
  server/src/main/java/com/alioth/server/common/config/SecurityConfig.java
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/contract/domain/Contract.java
  server/src/main/java/com/alioth/server/domain/contract/dto/req/ContractCreateDto.java
  server/src/main/java/com/alioth/server/domain/contract/dto/res/ContractResDto.java
  server/src/main/java/com/alioth/server/domain/contract/repository/ContractRepository.java
  server/src/main/java/com/alioth/server/domain/contract/service/ContractService.java
  server/src/main/java/com/alioth/server/domain/dummy/repository/CustomRepository.java
  server/src/main/java/com/alioth/server/domain/excel/controller/ExcelController.java
  server/src/main/java/com/alioth/server/domain/excel/domain/ExcelHeaders.java
  server/src/main/java/com/alioth/server/domain/excel/service/ExcelService.java
  server/src/main/java/com/alioth/server/domain/member/controller/SalesMemberController.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
  server/src/main/java/com/alioth/server/domain/team/repository/TeamRepository.java
  server/src/main/java/com/alioth/server/domain/team/service/TeamService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#46 보험의 신 작성
  statistics/src/main/java/com/alioth/statistics/controller/InsuranceGodController.java
  statistics/src/main/java/com/alioth/statistics/domain/contract/repository/ContractRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/insurance/dto/res/InsuranceGodResDto.java
  statistics/src/main/java/com/alioth/statistics/service/insurance/InsuranceGodService.java
  statistics/src/main/java/com/alioth/statistics/service/insurance/InsuranceGodServiceImpl.java
  statistics/src/test/java/com/alioth/statistics/service/insurance/InsuranceGodServiceImplTest.java
Labels: 🔼백엔드-개발, ✅테스트, 🍀코드리뷰

#50 배치 테스크 작업
  server/src/main/java/com/alioth/server/common/config/SecurityConfig.java
  server/src/main/java/com/alioth/server/domain/batch/BatchHQSales.java
  server/src/main/java/com/alioth/server/domain/batch/BatchMemberSales.java
  server/src/main/java/com/alioth/server/domain/batch/BatchRankMember.java
  server/src/main/java/com/alioth/server/domain/batch/BatchRankProduct.java
  server/src/main/java/com/alioth/server/domain/batch/BatchTeamSales.java
  server/src/main/java/com/alioth/server/domain/batch/repository/BatchHQSalesRepository.java
  server/src/main/java/com/alioth/server/domain/batch/repository/BatchMemberSalesRepository.java
  server/src/main/java/com/alioth/server/domain/batch/repository/BatchRankMemberRepository.java
  server/src/main/java/com/alioth/server/domain/batch/repository/BatchRankProductRepository.java
  server/src/main/java/com/alioth/server/domain/batch/repository/BatchTeamSalesRepository.java
  statistics/src/main/java/com/alioth/statistics/StatisticsApplication.java
  statistics/src/main/java/com/alioth/statistics/common/batch/job/JobConfiguration.java
  statistics/src/main/java/com/alioth/statistics/common/batch/scheduler/BatchScheduler.java
  statistics/src/main/java/com/alioth/statistics/common/batch/step/HqSalesStep.java
  statistics/src/main/java/com/alioth/statistics/common/batch/step/MemberSalesStep.java
  statistics/src/main/java/com/alioth/statistics/common/batch/step/RankMemberStep.java
  statistics/src/main/java/com/alioth/statistics/common/batch/step/RankProductStep.java
  statistics/src/main/java/com/alioth/statistics/common/batch/step/TeamSalesStep.java
  statistics/src/main/java/com/alioth/statistics/common/batch/tasklet/HqSalesTasklet.java
  statistics/src/main/java/com/alioth/statistics/common/batch/tasklet/MemberSalesTasklet.java
  statistics/src/main/java/com/alioth/statistics/common/batch/tasklet/RankMemberTasklet.java
  statistics/src/main/java/com/alioth/statistics/common/batch/tasklet/RankProductTasklet.java
  statistics/src/main/java/com/alioth/statistics/common/batch/tasklet/TeamSalesTasklet.java
  statistics/src/main/java/com/alioth/statistics/common/config/job/MemberTasklet.java
  statistics/src/main/java/com/alioth/statistics/common/config/job/SimpleJobConfiguration.java
  statistics/src/main/java/com/alioth/statistics/controller/BatchStatController.java
  statistics/src/main/java/com/alioth/statistics/controller/InsuranceProductController.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/BatchHQSales.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/BatchMemberSales.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/BatchRankMember.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/BatchRankProduct.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/BatchTeamSales.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/repository/BatchHQSalesRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/repository/BatchMemberSalesRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/repository/BatchRankMemberRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/repository/BatchRankProductRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/repository/BatchTeamSalesRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/contract/repository/ContractRepository.java
  statistics/src/main/resources/application.yml
  statistics/src/test/java/com/alioth/statistics/common/batch/tasklet/RankMemberTaskletTest.java
  statistics/src/test/java/com/alioth/statistics/common/batch/tasklet/TeamSalesTaskletTest.java
Labels: 🔼백엔드-개발, ✅테스트, 🍀코드리뷰

#58 Jh/password find06
  .gitignore
  server/src/main/java/com/alioth/server/common/config/FireBaseConfig.java
  server/src/main/java/com/alioth/server/common/config/SecurityConfig.java
  server/src/main/java/com/alioth/server/common/firebase/controller/FcmController.java
  server/src/main/java/com/alioth/server/domain/batch/repository/BatchHQSalesRepository.java
  server/src/main/java/com/alioth/server/domain/batch/repository/BatchMemberSalesRepository.java
  server/src/main/java/com/alioth/server/domain/batch/repository/BatchRankMemberRepository.java
  server/src/main/java/com/alioth/server/domain/batch/repository/BatchRankProductRepository.java
  server/src/main/java/com/alioth/server/domain/batch/repository/BatchTeamSalesRepository.java
  server/src/main/java/com/alioth/server/domain/contract/service/ContractService.java
  server/src/main/java/com/alioth/server/domain/login/controller/LoginController.java
  server/src/main/java/com/alioth/server/domain/login/service/LoginService.java
  server/src/main/java/com/alioth/server/domain/login/service/impl/LoginServiceImpl.java
  server/src/main/java/com/alioth/server/domain/member/controller/SalesMemberController.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
  server/src/main/resources/application.yml
  statistics/src/main/java/com/alioth/statistics/controller/InsuranceGodController 2.java
  statistics/src/main/java/com/alioth/statistics/service/insurance/InsuranceGodService 2.java
  statistics/src/main/java/com/alioth/statistics/service/insurance/InsuranceGodServiceImpl 2.java
  statistics/src/test/java/com/alioth/statistics/service/insurance/InsuranceGodServiceImplTest 2.java
Labels: 🍀코드리뷰

#59 [fix]: JWT 만료시 재발급 디버깅, 로그 제거
  server/src/main/java/com/alioth/server/common/jwt/JwtAuthFilter.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#60 JH/Board코드 수정
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/board/dto/res/BoardResDto.java
  server/src/main/java/com/alioth/server/domain/board/service/BoardService.java
  server/src/main/java/com/alioth/server/domain/contract/controller/ContractController.java
  server/src/main/java/com/alioth/server/domain/contract/dto/req/ContractCreateDto.java
  server/src/main/java/com/alioth/server/domain/contract/dto/res/ContractResDto.java
  server/src/main/java/com/alioth/server/domain/dummy/domain/ContractStatus.java
Labels: ⏫프론트-개발, 🔼백엔드-개발, 🍀코드리뷰

#61 [fix]: 마이페이지 정보 조회 기능 추가
  server/src/main/java/com/alioth/server/domain/member/controller/SalesMemberController.java
Labels: 🔼백엔드-개발, 🍀코드리뷰, ✅기타작업

#62 [fix]: SalesMemberController에서 path variable memberId에서 사번으로 수정
  server/src/main/java/com/alioth/server/domain/member/controller/SalesMemberController.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰, ✅기타작업

#63 Psj/fix 중복파일 제거
  statistics/src/main/java/com/alioth/statistics/controller/InsuranceGodController 2.java
  statistics/src/main/java/com/alioth/statistics/service/insurance/InsuranceGodService 2.java
  statistics/src/main/java/com/alioth/statistics/service/insurance/InsuranceGodServiceImpl 2.java
  statistics/src/test/java/com/alioth/statistics/service/insurance/InsuranceGodServiceImplTest 2.java
Labels: 🔼백엔드-개발, ✅기타작업

#65 Jgn/schedule vue
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/schedule/domain/Schedule.java
  server/src/main/java/com/alioth/server/domain/schedule/dto/req/ScheduleReqDto.java
  server/src/main/java/com/alioth/server/domain/schedule/dto/res/ScheduleResDto.java
Labels: 🔼백엔드-개발

#66 Psj/login fix 01
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/login/dto/res/LoginResDto.java
Labels: 🔼백엔드-개발

#67 Jh/contracterrorfix
  server/src/main/java/com/alioth/server/domain/contract/controller/ContractController.java
  server/src/main/java/com/alioth/server/domain/contract/dto/req/ContractUpdateDto.java
  server/src/main/java/com/alioth/server/domain/contract/repository/ContractRepository.java
  server/src/main/java/com/alioth/server/domain/contract/service/ContractService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#68 [fix]: contracterrorfix
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/board/dto/res/BoardResDto.java
  server/src/main/java/com/alioth/server/domain/contract/service/ContractService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#69 Jgn/schedule vue2
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/schedule/domain/Schedule.java
  server/src/main/java/com/alioth/server/domain/schedule/dto/req/ScheduleReqDto.java
  server/src/main/java/com/alioth/server/domain/schedule/dto/res/ScheduleResDto.java
  server/src/main/java/com/alioth/server/domain/schedule/repository/ScheduleRepository.java
  server/src/main/java/com/alioth/server/domain/schedule/service/ScheduleService.java
Labels: 🔼백엔드-개발

#70 Jh/code refactoring
  server/src/main/java/com/alioth/server/common/firebase/domain/FcmSendDto.java
  server/src/main/java/com/alioth/server/common/firebase/service/FcmServiceImpl.java
  server/src/main/java/com/alioth/server/domain/board/service/BoardService.java
  server/src/main/java/com/alioth/server/domain/contract/service/ContractService.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
  server/src/main/java/com/alioth/server/domain/notification/controller/NotificationController.java
  server/src/main/java/com/alioth/server/domain/notification/domain/Notification.java
  server/src/main/java/com/alioth/server/domain/notification/domain/ReadStatus.java
  server/src/main/java/com/alioth/server/domain/notification/dto/res/NotificationResDto.java
  server/src/main/java/com/alioth/server/domain/notification/repository/NotificationRepository.java
  server/src/main/java/com/alioth/server/domain/notification/service/NotificationService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#71 [fix]: salesMembers, team 관련 기능 수정 및 추가
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/excel/service/ExcelService.java
  server/src/main/java/com/alioth/server/domain/member/controller/SalesMemberController.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
  server/src/main/java/com/alioth/server/domain/team/controller/TeamController.java
  server/src/main/java/com/alioth/server/domain/team/dto/TeamResDto.java
  server/src/main/java/com/alioth/server/domain/team/repository/TeamRepository.java
  server/src/main/java/com/alioth/server/domain/team/service/TeamService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰, ✅기타작업

#75 HHJ/salesmembers_add
  server/src/main/java/com/alioth/server/domain/member/controller/SalesMemberController.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
  server/src/main/java/com/alioth/server/domain/team/dto/TeamReqDto.java
Labels: 🔼백엔드-개발, 🍀코드리뷰, ✅기타작업

#74 [fix]: excel controller get요청에서 post로 변경
  server/src/main/java/com/alioth/server/domain/excel/controller/ExcelController.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
Labels: 🔼백엔드-개발

#76 Hhj/fix_salesmember,team
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/member/controller/SalesMemberController.java
  server/src/main/java/com/alioth/server/domain/member/domain/SalesMembers.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
  server/src/main/java/com/alioth/server/domain/team/controller/TeamController.java
  server/src/main/java/com/alioth/server/domain/team/service/TeamService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰, ✅기타작업

#79 Psj/sales api 01
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/board/service/BoardService.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
  server/src/test/java/com/alioth/server/domain/answer/service/AnswerServiceTest.java
  statistics/src/main/java/com/alioth/statistics/common/batch/scheduler/BatchScheduler.java
  statistics/src/main/java/com/alioth/statistics/common/batch/step/HqSalesStep.java
  statistics/src/main/java/com/alioth/statistics/common/batch/step/MemberSalesStep.java
  statistics/src/main/java/com/alioth/statistics/common/batch/step/RankMemberStep.java
  statistics/src/main/java/com/alioth/statistics/common/batch/step/RankProductStep.java
  statistics/src/main/java/com/alioth/statistics/common/batch/step/TeamSalesStep.java
  statistics/src/main/java/com/alioth/statistics/controller/BatchStatController.java
  statistics/src/main/java/com/alioth/statistics/controller/StatController.java
  statistics/src/main/java/com/alioth/statistics/domain/achievementrate/dto/res/AchievementRateResDto.java
  statistics/src/main/java/com/alioth/statistics/domain/achievementrate/dto/res/HQAchievementRateResDto.java
  statistics/src/main/java/com/alioth/statistics/domain/achievementrate/dto/res/SMAchievementRateResDto.java
  statistics/src/main/java/com/alioth/statistics/domain/achievementrate/dto/res/TeamAchievementRateResDto.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/BatchRankProduct.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/dto/res/BatchHQSalesResDto.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/dto/res/BatchTeamSalesResDto.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/repository/BatchHQSalesRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/repository/BatchTeamSalesRepository.java
  statistics/src/main/java/com/alioth/statistics/service/stat/StatHQSalesService.java
  statistics/src/main/java/com/alioth/statistics/service/stat/StatMemberSalesService.java
  statistics/src/main/java/com/alioth/statistics/service/stat/StatProductService.java
  statistics/src/main/java/com/alioth/statistics/service/stat/StatTeamSalesService.java
  statistics/src/test/java/com/alioth/statistics/service/AchievementRateTest.java
  statistics/src/test/java/com/alioth/statistics/service/stat/BatchStatProductServiceTest.java
  statistics/src/test/java/com/alioth/statistics/service/stat/BatchStatServiceTest.java
Labels: 🔼백엔드-개발, ✅테스트

#78 [fix] 게시판 코드 수정
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/answer/domain/Answer.java
  server/src/main/java/com/alioth/server/domain/answer/dto/req/AnswerReqDto.java
  server/src/main/java/com/alioth/server/domain/board/controller/BoardController.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
Labels: ⏫프론트-개발, 🍀코드리뷰

#80 Hhj/teamDelete
  server/src/main/java/com/alioth/server/domain/excel/controller/ExcelController.java
  server/src/main/java/com/alioth/server/domain/excel/service/ExcelService.java
  server/src/main/java/com/alioth/server/domain/member/controller/SalesMemberController.java
  server/src/main/java/com/alioth/server/domain/member/domain/SalesMembers.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
  server/src/main/java/com/alioth/server/domain/team/controller/TeamController.java
  server/src/main/java/com/alioth/server/domain/team/service/TeamService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰, ✅기타작업

#81 Hhj/address
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/common/init/DataInitialization.java
  server/src/main/java/com/alioth/server/domain/member/domain/SalesMembers.java
  server/src/main/java/com/alioth/server/domain/member/dto/req/SalesMemberCreateReqDto.java
  server/src/main/java/com/alioth/server/domain/member/dto/req/SalesMemberUpdateReqDto.java
  server/src/main/java/com/alioth/server/domain/member/dto/res/SMTeamListResDto.java
  server/src/main/java/com/alioth/server/domain/member/dto/res/SalesMemberResDto.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
  server/src/main/java/com/alioth/server/domain/team/controller/TeamController.java
  server/src/main/java/com/alioth/server/domain/team/service/TeamService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰, ✅기타작업

#82 [fix] backend codefix
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/answer/domain/Answer.java
  server/src/main/java/com/alioth/server/domain/dummy/controller/DummyController.java
  server/src/main/java/com/alioth/server/domain/dummy/dto/res/SimpleListDTO.java
  server/src/main/java/com/alioth/server/domain/dummy/service/DummyService.java
  server/src/main/java/com/alioth/server/domain/login/service/impl/LoginServiceImpl.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
  server/src/main/java/com/alioth/server/domain/notification/controller/NotificationController.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#84 [feat] : 계약 필터 수정
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/contract/dto/res/ContractResDto.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#83 Jh/membercode validate
  server/src/main/java/com/alioth/server/common/config/SecurityConfig.java
  server/src/main/java/com/alioth/server/domain/login/controller/LoginController.java
  server/src/main/java/com/alioth/server/domain/member/controller/SalesMemberController.java
  server/src/main/java/com/alioth/server/domain/member/repository/SalesMemberRepository.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#87 Psj/login sideber 01
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/login/dto/res/LoginResDto.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
Labels: 🔼백엔드-개발

#88 Psj/hotfix 0
  server/src/main/java/com/alioth/server/domain/board/service/BoardService.java
  statistics/src/main/java/com/alioth/statistics/controller/StatController.java
  statistics/src/main/java/com/alioth/statistics/service/stat/StatMemberSalesService.java
Labels: 🔼백엔드-개발

#89 프로필 이미지 수정
  server/build.gradle
  server/src/main/java/com/alioth/server/common/aws/S3Config.java
  server/src/main/java/com/alioth/server/common/aws/S3Service.java
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/member/controller/SalesMemberController.java
  server/src/main/java/com/alioth/server/domain/member/domain/SalesMembers.java
  server/src/main/java/com/alioth/server/domain/member/dto/req/SalesMemberImageReqDto.java
  server/src/main/java/com/alioth/server/domain/member/dto/res/SalesMemberResDto.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
Labels: 🔼백엔드-개발

#90 [fix]: 영업사원 RANK에 따라 건의사항 작성시 알람을 받는 범위 수정 및 hq직원도 건의사항 작성가능
  server/src/main/java/com/alioth/server/common/response/CommonResponse.java
  server/src/main/java/com/alioth/server/domain/board/service/BoardService.java
  server/src/main/java/com/alioth/server/domain/member/repository/SalesMemberRepository.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
  server/src/test/java/com/alioth/server/domain/team/service/TeamServiceTest.java
Labels: 🔼백엔드-개발

#91 Hhj/fix_teamNsalesMembers
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/contract/repository/ContractRepository.java
  server/src/main/java/com/alioth/server/domain/contract/service/ContractService.java
  server/src/main/java/com/alioth/server/domain/excel/controller/ExcelController.java
  server/src/main/java/com/alioth/server/domain/excel/service/ExcelService.java
  server/src/main/java/com/alioth/server/domain/member/controller/SalesMemberController.java
  server/src/main/java/com/alioth/server/domain/member/domain/SalesMembers.java
  server/src/main/java/com/alioth/server/domain/member/dto/req/SalesMemberUpdateReqDto.java
  server/src/main/java/com/alioth/server/domain/member/dto/res/SMTeamListResDto.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
  server/src/main/java/com/alioth/server/domain/notification/controller/NotificationController.java
  server/src/main/java/com/alioth/server/domain/team/controller/TeamController.java
  server/src/main/java/com/alioth/server/domain/team/dto/TeamResDto.java
  server/src/main/java/com/alioth/server/domain/team/service/TeamService.java
Labels: 🔼백엔드-개발
