Repository GyeongNam/Alioth-Back, pull requests merged in 2024-05, with the labels that each got.

#93 HHJ/fix-noTeamIssue
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
Labels: 🔼백엔드-개발, ✅기타작업

#95 Hhj/fix
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/common/response/CommonResponse.java
  server/src/main/java/com/alioth/server/domain/member/controller/SalesMemberController.java
  server/src/main/java/com/alioth/server/domain/member/domain/SalesMembers.java
  server/src/main/java/com/alioth/server/domain/member/dto/req/SalesMemberUpdateReqDto.java
  server/src/main/java/com/alioth/server/domain/member/service/SalesMemberService.java
Labels: 🔼백엔드-개발

#94 [fix]: 코드수정
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/answer/dto/res/AnswerResDto.java
  server/src/main/java/com/alioth/server/domain/contract/dto/res/ContractResDto.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#96 배포 Create gradle.yml 생성
  .github/workflows/gradle.yml
Labels: 🛰데브옵스-개발, ✅테스트

#97 HHJ/fix-profileDefault
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
Labels: 🔼백엔드-개발

#103 Psj/sales 01 update re05
  server/.gitignore
  server/src/main/java/com/alioth/server/AliothApplication.java
  server/src/main/java/com/alioth/server/common/aws/S3Service.java
  server/src/main/java/com/alioth/server/common/image/service/ImageService.java
  server/src/main/java/com/alioth/server/domain/board/controller/BoardController.java
  server/src/main/java/com/alioth/server/domain/board/dto/req/SugBoardImageReqDto.java
  server/src/main/java/com/alioth/server/domain/board/service/BoardService.java
  server/src/main/java/com/alioth/server/domain/member/controller/SalesMemberController.java
  server/src/main/java/com/alioth/server/domain/member/dto/req/SalesMemberUpdateReqDto.java
  server/src/test/java/com/alioth/server/domain/answer/service/AnswerServiceTest.java
  server/src/test/java/com/alioth/server/domain/board/service/BoardServiceTest.java
  server/src/test/java/com/alioth/server/domain/member/service/SalesMemberServiceTest.java
  server/src/test/java/com/alioth/server/domain/schedule/service/ScheduleServiceTest.java
  server/src/test/java/com/alioth/server/domain/team/service/TeamServiceTest.java
  statistics/src/main/java/com/alioth/statistics/controller/StatController.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/repository/BatchMemberSalesRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/batch/repository/BatchRankMemberRepository.java
  statistics/src/main/java/com/alioth/statistics/sales/controller/SalesController.java
  statistics/src/main/java/com/alioth/statistics/sales/controller/SalesPersonalController.java
  statistics/src/main/java/com/alioth/statistics/sales/controller/SalesRankingController.java
  statistics/src/main/java/com/alioth/statistics/sales/controller/SalesTeamController.java
  statistics/src/main/java/com/alioth/statistics/sales/controller/SalesTotalController.java
  statistics/src/main/java/com/alioth/statistics/sales/dto/res/SalesMemberRankResDto.java
  statistics/src/main/java/com/alioth/statistics/sales/dto/res/SalesPerformanceResDto.java
  statistics/src/main/java/com/alioth/statistics/sales/dto/res/SalesPersonalListResDto.java
  statistics/src/main/java/com/alioth/statistics/sales/service/SalesRankingService.java
  statistics/src/main/java/com/alioth/statistics/service/stat/StatProductService.java
  statistics/src/test/java/com/alioth/statistics/service/cencellation/rank/TeamCancellationServiceTest.java
Labels: 🔼백엔드-개발

#105 Jgn/excel kr
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/contract/dto/res/ContractExcelResDto.java
  server/src/main/java/com/alioth/server/domain/excel/service/ExcelService.java
  server/src/main/java/com/alioth/server/domain/member/dto/res/SalesMemberResDto.java
Labels: 🔼백엔드-개발

#106 Psj/sales 05
  server/src/main/java/com/alioth/server/common/domain/BaseEntity.java
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  statistics/src/main/java/com/alioth/statistics/common/domain/BaseEntity.java
  statistics/src/main/java/com/alioth/statistics/dashboard/controller/DashboardController.java
  statistics/src/main/java/com/alioth/statistics/dashboard/dto/res/DashboardBestTeamResDto.java
  statistics/src/main/java/com/alioth/statistics/dashboard/dto/res/DashboardBoardResDto.java
  statistics/src/main/java/com/alioth/statistics/dashboard/dto/res/DashboardGodResDto.java
  statistics/src/main/java/com/alioth/statistics/dashboard/service/DashboardBoardService.java
  statistics/src/main/java/com/alioth/statistics/dashboard/service/DashboardGodService.java
  statistics/src/main/java/com/alioth/statistics/domain/board/domain/Board.java
  statistics/src/main/java/com/alioth/statistics/domain/board/repository/BoardRepository.java
  statistics/src/main/java/com/alioth/statistics/domain/contract/repository/ContractRepository.java
  statistics/src/test/java/com/alioth/statistics/dashboard/service/DashboardBoardServiceTest.java
  statistics/src/test/java/com/alioth/statistics/dashboard/service/DashboardServiceTest.java
  statistics/src/test/java/com/alioth/statistics/service/MemberRankServiceTest.java
Labels: 🔼백엔드-개발

#107 Hhj/fix team
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/answer/domain/Answer.java
  server/src/main/java/com/alioth/server/domain/answer/dto/res/AnswerResDto.java
  server/src/main/java/com/alioth/server/domain/answer/service/AnswerService.java
  server/src/main/java/com/alioth/server/domain/board/dto/res/BoardResDto.java
  server/src/main/java/com/alioth/server/domain/member/controller/SalesMemberController.java
  server/src/main/java/com/alioth/server/domain/member/domain/SalesMembers.java
  server/src/main/java/com/alioth/server/domain/member/dto/req/SMAdminUpdateReqDto.java
  server/src/main/java/com/alioth/server/domain/member/dto/req/SalesMemberCreateReqDto.java
  server/src/main/java/com/alioth/server/domain/member/dto/req/SalesMemberUpdateReqDto.java
  server/src/main/java/com/alioth/server/domain/member/dto/res/SalesMemberResDto.java
  server/src/main/java/com/alioth/server/domain/team/domain/Team.java
  server/src/main/java/com/alioth/server/domain/team/dto/TeamReqDto.java
  server/src/main/java/com/alioth/server/domain/team/dto/TeamResDto.java
Labels: 🔼백엔드-개발

#109 [fix]: 게시판 관련 dto 수정
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/answer/domain/Answer.java
  server/src/main/java/com/alioth/server/domain/answer/dto/res/AnswerResDto.java
  server/src/main/java/com/alioth/server/domain/board/domain/Board.java
  server/src/main/java/com/alioth/server/domain/contract/domain/Contract.java
  server/src/main/java/com/alioth/server/domain/member/dto/res/SalesMemberResDto.java
Labels: 🔼백엔드-개발

#110 [feat] 매출 전사 api
  statistics/src/main/java/com/alioth/statistics/sales/controller/SalesController.java
  statistics/src/main/java/com/alioth/statistics/sales/dto/res/SalesHQTotalPriceResDto.java
  statistics/src/main/java/com/alioth/statistics/sales/dto/res/SalesHQTotalTeamPriceResDto.java
  statistics/src/main/java/com/alioth/statistics/sales/service/SalesHQService.java
Labels: 🔼백엔드-개발

#113 Psj/sales hq 01
  statistics/src/main/java/com/alioth/statistics/sales/controller/SalesController.java
  statistics/src/main/java/com/alioth/statistics/sales/controller/SalesRankingController.java
Labels: 🔼백엔드-개발
