Repository GyeongNam/Alioth-Back, pull requests merged in 2024-03, with the labels that each got.

#1 [feat]: server package create
  server/src/main/java/com/alioth/server/common/config/RedisConfig.java
  server/src/main/java/com/alioth/server/common/domain/BaseEntity.java
  server/src/main/java/com/alioth/server/common/handler/AccessDeniedHandler.java
  server/src/main/java/com/alioth/server/common/handler/CustomAuthenticationEntryPointHandler.java
  server/src/main/java/com/alioth/server/common/jwt/JwtAuthFilter.java
  server/src/main/java/com/alioth/server/common/response/ExceptionResponse.java
  server/src/main/java/com/alioth/server/domain/login/dto/LoginReqDto.java
  server/src/main/resources/application.yml
  statistics/src/main/resources/application.yml
Labels: documentation

#15 Jh/contract crud 4
  server/src/main/java/com/alioth/server/domain/contract/controller/ContractController.java
  server/src/main/java/com/alioth/server/domain/contract/domain/Contract.java
  server/src/main/java/com/alioth/server/domain/contract/domain/Renewal.java
  server/src/main/java/com/alioth/server/domain/contract/dto/req/ContractCreateDto.java
  server/src/main/java/com/alioth/server/domain/contract/dto/req/ContractUpdateDto.java
  server/src/main/java/com/alioth/server/domain/contract/dto/res/ContractResDto.java
  server/src/main/java/com/alioth/server/domain/contract/repository/ContractRepository.java
  server/src/main/java/com/alioth/server/domain/contract/repository/RenewalRepository.java
  server/src/main/java/com/alioth/server/domain/contract/service/ContractService.java
  server/src/main/java/com/alioth/server/domain/dummy/service/DummyService.java
Labels: help wanted

#20 시큐리티 수정
  server/src/main/java/com/alioth/server/common/config/SecurityConfig.java
  server/src/main/java/com/alioth/server/common/jwt/JwtAuthFilter.java
  server/src/main/java/com/alioth/server/common/jwt/JwtTokenProvider.java
  server/src/main/java/com/alioth/server/domain/login/controller/LoginController.java
  server/src/main/java/com/alioth/server/domain/member/dto/req/SalesMemberCreateReqDto.java
  server/src/test/java/com/alioth/server/domain/member/service/SalesMemberServiceTest.java
Labels: 🍀코드리뷰

#21 Jgn/schedule re
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/board/controller/BoardController.java
  server/src/main/java/com/alioth/server/domain/dummy/controller/DummyController.java
  server/src/main/java/com/alioth/server/domain/schedule/controller/ScheduleController.java
  server/src/main/java/com/alioth/server/domain/schedule/domain/Schedule.java
  server/src/main/java/com/alioth/server/domain/schedule/dto/req/ScheduleCreateDto.java
  server/src/main/java/com/alioth/server/domain/schedule/dto/req/ScheduleReqDto.java
  server/src/main/java/com/alioth/server/domain/schedule/service/ScheduleService.java
  server/src/test/java/com/alioth/server/domain/schedule/service/ScheduleServiceTest.java
Labels: 🔼백엔드-개발

#22 초기 데이터 생성
  server/src/main/java/com/alioth/server/common/init/DataInitialization.java
Labels: 🔼백엔드-개발, 🍀코드리뷰

#23 Psj/member fix
  server/src/main/java/com/alioth/server/common/init/DataInitialization.java
  server/src/main/java/com/alioth/server/common/jwt/JwtAuthFilter.java
  server/src/main/java/com/alioth/server/domain/member/domain/SalesMembers.java
Labels: 🔼백엔드-개발

#25 Swagger 적용
  server/build.gradle
  server/src/main/java/com/alioth/server/common/config/SecurityConfig.java
  server/src/main/java/com/alioth/server/common/config/SwaggerConfig.java
Labels: 🔼백엔드-개발, ✅기타작업

#26 Jgn/board re2
  server/src/main/java/com/alioth/server/domain/board/controller/BoardController.java
  server/src/main/java/com/alioth/server/domain/board/dto/req/BoardUpdateDto.java
  server/src/main/java/com/alioth/server/domain/board/repository/BoardRepository.java
  server/src/main/java/com/alioth/server/domain/board/service/BoardService.java
  server/src/test/java/com/alioth/server/domain/board/service/BoardServiceTest.java
  server/src/test/java/com/alioth/server/domain/schedule/service/ScheduleServiceTest.java
Labels: 🔼백엔드-개발, ✅테스트, 🍀코드리뷰

#28 Jh/contract crud 7
  server/src/main/java/com/alioth/server/common/config/SecurityConfig.java
  server/src/main/java/com/alioth/server/common/domain/TypeChange.java
  server/src/main/java/com/alioth/server/domain/contract/controller/ContractController.java
  server/src/main/java/com/alioth/server/domain/contract/service/ContractService.java
  server/src/main/java/com/alioth/server/domain/dummy/service/DummyService.java
  server/src/test/java/com/alioth/server/domain/contract/service/ContractServiceTest.java
Labels: 🍀코드리뷰
